tor:
  address: purednsxr4shjkobosrqf7qebwzch3e4ignfr4beq34ngr4nkp2z32id.onion
  port: 53
manual:
  - dns.testing-only.: 127.0.53.2
  - local.testing.pvt.: 127.0.4.2
  - pure.privatedomain.: 127.1.5.6