name: Deploy PR

on:
  push:
    branches: [ master ]

jobs:
  deployPR:
    name: Deploy PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Publish Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t "habibiefaried/dns-over-tor-resolver:latest"
          docker push "habibiefaried/dns-over-tor-resolver:latest"