name: Deploy Docker PR

on:
  pull_request:
    branches: [ master ]

jobs:
  deployDockerPR:
    name: Deploy Docker PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Publish Docker image (Branch)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t "habibiefaried/dns-over-tor-resolver:pr-${{ github.event.number }}"
          docker push "habibiefaried/dns-over-tor-resolver:pr-${{ github.event.number }}"