name: "Unit Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Testing
      run: |
        go test -v ./...